.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 iBroadcast Media, LLC <ryan@ibroadcast.com>,
.\"
.TH MEDIASYNCLITE 1 "August 2026" "mediasynclite" "User Commands"
.SH NAME
mediasynclite \- Upload your music library to your iBroadcast account
.SH SYNOPSIS
.B mediasynclite
.SH DESCRIPTION
.B mediasynclite
is a native GTK application that scans a local music library,
reads ID3v2/ID3v1 and Vorbis-comment tags where available, and uploads new
tracks to your iBroadcast cloud account. It performs MD5- and tag-based
duplicate detection so previously uploaded tracks are not sent again.
.PP
A desktop entry and application icon are installed alongside the binary,
so
.B mediasynclite
can also be launched from your desktop environment's application menu.
.SH OPTIONS
This is a GUI program and there are no command-line options.
.SH SEE ALSO
Homepage: https://github.com/iBroadcastMediaServices/MediaSyncLiteLinux
.SH AUTHOR
iBroadcast Media, LLC <ryan@ibroadcast.com>
